### ISSUE TITLE
Include username in constructud @mentions

### ISSUE THREAD

**Issue by slacksoc** [brenns10/slacksoc#35]
This works around an issue where some clients don't have a user ID loaded, and so they show an ellipsis rather than a username.

Created via Slack on behalf of brenns10 (Stephen Brennan)

**Comment by brenns10** [comment]
This is more of a *slack* bug than a *slacksoc* bug, but I think we can avoid it by simply by including the username like this `<@UXXXXXXXX|username>`.

It seems that some clients (chrome Windows 10, IE Windows 10, and Firefox OS unspecified) will have trouble filling out the username portion of some `@mentions`, particularly for users that haven't been doing much recently, I guess?  Somehow, it seems that the user gets left out of their user list, and doesn't get added until they visit that user's profile page. Then if they navigate back to the chat history the `@mention` displays properly. While I think that is rather silly and inconsistent client behavior, there is an `@mention` syntax that will get around this, and I think that most clients send using that syntax anyway, so I should be using it.

I wonder if I can send a mention with any text...
